### ISSUE TITLE
What to charge attendees?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#2]
I love free and the SQLSats are free with the ability to add up to £10 for lunches. I would really like these to be free as it means anyone can attend so long as they can get there. We should however agree what we will intend to charge, what we can charge, and why we're doing these so that we start off on the right footing.

There are however, two areas that free can cause some pain:
1.  When you charge even a nominal sum the dropout rate goes down so you don't have to get as many people registered. A conf called SQL in the City, went from free with a 50% dropout rate, to £50 (~$75 USD) with 10% dropout. 
2. Free means you have to get all the funds from sponsors, or pay the gap off your back as the event organiser - this can be _really_ hairy and stressful for an event organiser. Having some cash from every registrant reduces the amount of sponsorship required. Especially in the early days, it might be might tough finding enough sponsors willing to contribute.

So what are people's thoughts either way?

**Comment by philbudden** [comment]
I'd be willing to pay a nominal charge to attend something like this providing it's not too high.  There are a lot of conferences I'd happily attend that I'm priced out of unless I submit a business case for my employer to fund them.  Not sure how much it costs to organise but I think if you could price it around £30/£40 I wouldn't have an issue paying it (more than that and I have to justify it to my better half!)

**Comment by stephlocke** [comment]
I get it - keep it cheaper than an xbox game ;-)

**Comment by philbudden** [comment]
Exactly ;-)

**Comment by ZoeLocke** [comment]
Yeah, as soon as you have to get a manager to sign off on something the chances of even making it are way lower

**Comment by sqldiver** [comment]
I'm quite happy to pay a small fee and completely understand that charging a nominal fee helps reduce the dropout rate.  A couple of thoughts on sponsors:
1. Making the conference capability focussed as opposed to technology focussed may attract a wider range of investors.
2. Since Microsoft are supporting R in SQL Server 2016, they may be willing to support an event which caters for SQL Server users.
3. Specialist recruitment agencies, or companies looking to recruit those with R skills and data science knowledge may be keen to support such an event.  This may have a bearing on where the event is hosted.

**Comment by daroczig** [comment]
I think a nominal fee (like 50 USD) is totally fine, even in Eastern Europe, where I'm from, and should be OK for students as well. And the two points mentioned by @stephlocke are IMO very important ones.

On the other hand, I'd also think about a sponsorship program, so that anyone can attend the event after applying for sponsorship -- which simply means free entry. The sponsorship program could be a simple Google Form including info on name, organization, employment status (like student) and a short but required comment box on why applying for sponsorship.

I think this would keep the number of false RSVPs at a minimal rate, yet providing some extra funding for the event and letting anyone attend for free. I think the overhead of this sponsorship program would be relatively small, eg a group of 2 or 3 persons reviewing the responses and voting on approval shouldn't take more than a few hours. What do you think?

**Comment by stephlocke** [comment]
I like it

So broad consensus seems to be that we should allow charging up to a certain amount (~£30), but have a budgeted amount of free slots available for people who need it

**Comment by sqldiver** [comment]
This sounds reasonable.  This way people are not being restricted based on their means to pay.
