### ISSUE TITLE
What typical format?

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#3]
What sort of format should the RSats take?

The SQLSats have a fairly standard conference model, and then do workshops on the Friday which are usually charged to attendees. The sessions are also typically an hour long.

What do we want our conferences to look like by default? What do we think are great ideas to incorporate from day 1 and what should we definitely not do?

**Comment by ZoeLocke** [comment]
I'd say like the SQL conferences we've been to, but I'm biased. Kind of depends on what R attendees would want

**Comment by daroczig** [comment]
Besides regular talks, I think having lightning talks (5 mins, 15 slides as at useR! conferences) is a must!

**Comment by stephlocke** [comment]
Great idea

**Comment by sqldiver** [comment]
I think that a conference can do more than just a series of talks - what about interaction?  If you are able to engage directly with the community, this can help understand their requirements better and plan more effectively for future conferences.  At SQLSatuday in Exeter this year, a competition was held - A dataset was made available and people were invited to give a brief presentation telling a story using the visualisation software of their choice.  I thought this is an excellent way to involve the community, whilst sharing creative problem-solving approaches.

I would also suggest enabling individual conferences to have a certain degree of autonomy, so that different ideas can be explored and conferences can be tailored to cater for a variety of skills/individual preferences of those taking part.
