### ISSUE TITLE
What should our central platform do? (if we have one)

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/RSaturday-proposal#5]
What would we like to build to support the RSats?

For the sorts of things it could do, here's what the SQLSat platform currently does:
- homepage for each conference
- calendar of conferences
- enables attendee registration
- print-off tickets (inc for sponsor competitions)
- speaker submission
- agenda making and publication
- email notifications for past speakers about new events
- volunteer sign up and management
- charging platform for events charging a lunch price
- sponsor management
- central event approval workflow for admins

Alternatively, the Security B-Sides conferences don't provide a central platform and expect folks to do it all themselves, providing just some guidance.

**Comment by daroczig** [comment]
If charging a fee (being discussed at #2), then having a central platform for ticketing and handling money would be very helpful -- using some services like https://sched.org and/or https://www.eventbrite.com might save us a lot of time spent on administration and custom hacks.

**Comment by sqldiver** [comment]
I agree that using a service like eventbrite for ticketing will save a lot of hassle.  It may not be possible to have a central platform from day one - social media and other tools can be used to manage events, whilst a website is built.  I think one central platform is better than individual implementations - otherwise this would be a big burden for event organisers.  For the architecture, I would suggest using something like WordPress or BuddyPress.  From a visual perspective, a brand identity will be needed - Logo(s), font, colours.

Additional features:
- News
- Speaker Profiles
- Speaker Blogs
- Integration with Twitter/other social media
- Resources (slide downloads, supporting links for sessions)
- Webcasts
- Links

**Comment by stephlocke** [comment]
We'll start a product backlog for when we do the implementation
